"""empty message

Revision ID: 87d5fe3d8113
Revises: d8fc5179ba8d
Create Date: 2016-06-04 02:58:56.034000

"""

# revision identifiers, used by Alembic.
revision = '87d5fe3d8113'
down_revision = 'd8fc5179ba8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('valve_techincal_data', 'seatPressure')
    # op.drop_column('valve_techincal_data', 'seatPressureUnit')
    op.add_column('valve_test_report', sa.Column('leakage', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valve_test_report', 'leakage')
    # op.add_column('valve_techincal_data', sa.Column('setPressureUnit', sa.VARCHAR(length=12), nullable=True))
    # op.add_column('valve_techincal_data', sa.Column('setPressure', sa.FLOAT(), nullable=True))
    ### end Alembic commands ###
